const clientRouterEndPoints = {
  //me
  me: "/client/me",
  updateClient: "/client/update",
  getAllCategories: "/client/categories",
  getSpecialitiesWithSkills: "/client/specialities",
  createJob: "/client/jobs",
  getAllJobs: "/client/jobs",
  getJobDetail: (jobId:string)=>`/client/jobs/${jobId}`,
  updateJobDetail:(jobId:string)=>`/client/jobs/${jobId}`,
  closeJob: (jobId:string)=>`/client/jobs/${jobId}/close`,
  getAllFreelancers:"/client/freelancers",
  getFreelancerDetail:(freelancerId:string)=>`/client/freelancers/${freelancerId}`,
  saveFreelancer:(freelancerId:string)=>`/client/freelancers/${freelancerId}/save`,
  isFreelancerSaved:(freelancerId:string)=>`/client/freelancers/${freelancerId}/saved`,
  getSavedFreelancers: "/client/saved-freelancers",
  createOffer: "/client/offers",
  getOffers: "/client/offers",
  getOfferDetail: (offerId: string) => `/client/offers/${offerId}`,
  withdrawOffer: (offerId: string) => `/client/offers/${offerId}/withdraw`,
  getAllFreelancerPortfolio:(freelancerId:string)=>`/client/freelancers/${freelancerId}/portfolio`,
  getAllJobProposals:(jobId:string)=>`/client/jobs/${jobId}/proposals`,
  getProposalDetail:(proposalId:string)=>`/client/proposals/${proposalId}`,
  rejectProposal:(proposalId:string)=>`/client/proposals/${proposalId}/reject`,
  getContracts:"/client/contracts",
  getContractDetail:(contractId:string)=>`/client/contracts/${contractId}`,
  cancelContract:(contractId:string)=>`/client/contracts/${contractId}/cancel`,
  initiatePayment:"/client/payments/initiate",
  paymentCallback:"/client/payments/callback",
  sendChatMessage: "/client/chat/send",
  getChatMessages: (contractId: string) => `/client/chat/${contractId}/messages`,
  markChatAsRead: "/client/chat/read",
  getChatUnreadCount: (contractId: string) => `/client/chat/${contractId}/unread-count`,
  getMilestoneDetail: (contractId: string, milestoneId: string) => `/client/contracts/${contractId}/milestones/${milestoneId}`,
  approveDeliverable: (contractId: string) => `/client/contracts/${contractId}/deliverables/approve`,
  requestDeliverableChanges: (contractId: string) => `/client/contracts/${contractId}/deliverables/request-changes`,
  approveMilestoneDeliverable: (contractId: string) => `/client/contracts/${contractId}/milestones/deliverables/approve`,
  requestMilestoneChanges: (contractId: string) => `/client/contracts/${contractId}/milestones/deliverables/request-changes`,
  respondToMilestoneExtension: (contractId: string) => `/client/contracts/${contractId}/milestones/extension/respond`,
  getContractWorklogs: (contractId: string) => `/client/contracts/${contractId}/worklogs`,
  getWorklogDetail: (contractId: string, worklogId: string) => `/client/contracts/${contractId}/worklogs/${worklogId}`,
  approveWorklog: (contractId: string) => `/client/contracts/${contractId}/worklogs/approve`,
  rejectWorklog: (contractId: string) => `/client/contracts/${contractId}/worklogs/reject`,
};

export default clientRouterEndPoints;
